name: staticman
version: 2
allowedHosts:
  - lamarysedoree.github.io
repositories:
  - name: "lamarysedoree/lamarysedoree.github.io"
    branch: "main"
    path: "comments"
    filename: "comment-{{ date }}-{{ index }}.json"
